site_name: "botathon-2024-front"
site_description: "botathon 2024 front"

nav:
  - Introduction: index.md
  - API Reference:
      - Overview: website.md
      - Endpoints: endpoints.md

plugins:
  - techdocs-core