name: Deploy Frontend to GCP VM
on:
  push:
    branches: [ main ] 
  workflow_dispatch: 
env:
  SERVER_DIR: /root/frontend-teleton/teleton-chatbot-frontend
  DEPLOY_DIR: /var/www/teleton/
jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Deploy to GCP VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 34.132.204.3
          username: vce923
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script_stop: true
          script: |
            sudo bash -c '
              cd ${{ env.SERVER_DIR }} &&
              git pull &&
              npm install &&
              npm run build &&
              cp -R dist/* ${{ env.DEPLOY_DIR }} &&
              systemctl daemon-reload &&
              systemctl restart nginx
            '
