name: Deploy to GCP VM
on:
  push:
    branches: [ main ] 
  workflow_dispatch: 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to GCP VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 34.132.204.3
          username: vce923
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            sudo bash -c '
              cd /root/frontend-teleton/teleton-chatbot-frontend &&
              # Handle potential local changes to prevent pull failures
              git checkout -- package.json package-lock.json &&
              git pull &&
              npm install &&
              npm run build &&
              cp -R dist/* /var/www/teleton/ &&
              systemctl daemon-reload &&
              systemctl restart nginx
            '
