name: Sync Repository to Personal Repo

on:
  workflow_dispatch:

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GH_KIROVICH_AI_DEPLOY_KEYS }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Push to Private Repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote add kirovich-ai-repo git@github.com:kirovich-ai/teleton-chatbot-frontend.git
          git push -f -u kirovich-ai-repo main
