name: Sync to External Repo (Selective)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GH_KIROVICH_AI_DEPLOY_KEYS }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Verify SSH Connection
        run: ssh -T git@github.com || true

      - name: Git Config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add Remote Repo
        run: |
          git remote add external git@github.com:kirovich-ai/teleton-chatbot-frontend.git
          git remote -v

      - name: Create temporary sync branch
        run: |
          git checkout -b sync-temp

      - name: Remove .github/workflows except allowlisted ones
        run: |
          mkdir -p .github/workflows
          cp .github/workflows/test.yaml .github/workflows/ 2>/dev/null || true  # ejemplo
          git rm -r --cached .github/workflows || true
          git add .github/workflows
          git commit -m "Sync without most workflows" || echo "No changes to commit"

      - name: Push to External Repo (Selective with Retry)
        run: |
          for i in {1..5}; do
            git push -f external sync-temp:main && break || {
              echo "Retry $i failed, retrying in 5s..."
              sleep 5
            }
          done
