name: Sync to Private Repo

on:
  workflow_dispatch:

jobs:
  sync-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Trae todo el historial

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GH_KIROVICH_AI_DEPLOY_KEYS }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Set Git Config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create Clean Branch Without .github/workflows
        run: |
          git checkout -b temp-sync-branch
          git rm -r --cached .github/workflows || true
          git restore --staged .github/workflows || true
          git commit -am "Sync update (excluding workflows)" || echo "No changes to commit"

      - name: Add Private Repo Remote
        run: |
          git remote add kirovich git@github.com:kirovich-ai/teleton-chatbot-frontend.git

      - name: Force Push to Private Repo with Retry
        run: |
          for i in {1..5}; do
            git push -f kirovich temp-sync-branch:main && break || sleep 5
          done

      - name: Cleanup (Delete Temporary Branch)
        run: |
          git checkout main
          git branch -D temp-sync-branch || true
