name: Sync to Private Repo

on:
  push:
    branches: [ main ] 
  workflow_dispatch:

jobs:
  sync-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GH_KIROVICH_AI_DEPLOY_KEYS }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone Destination Repo into /tmp
        run: |
          git clone git@github.com:kirovich-ai/teleton-chatbot-frontend.git /tmp/sync-repo

      - name: Sync Files Except .github/workflows
        run: |
          rsync -av --delete --exclude='.github/workflows' ./ /tmp/sync-repo/

      - name: Remove .github/workflows directory from git tracking
        run: |
          cd /tmp/sync-repo
          git rm -rf --cached .github/workflows || true
          rm -rf .github/workflows

      - name: Commit and Push to Destination Repo
        run: |
          cd /tmp/sync-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Sync from organizational repo (excluding workflows)" || echo "No changes to commit"
          
          for i in {1..5}; do
            git push origin main && break || sleep 5
          done
